### ISSUE TITLE
Phive package

### ISSUE THREAD

**Issue by peldax** [j6s/phparch#6]
Hi,
I currently discovered this project and I would like to integrate it into my project.
I am using Phive https://phar.io/ for my tool packages in order to avoid dependency hell between various analyzers, is there any chance you would create phive package for this project? :+1: 

Thank you.

**Comment by j6s** [comment]
I think you may have misunderstood the nature of this package. PHPArch is not a standalone tool - it is a library that is meant to be used in a testing codebase. As such having it inside of a package manager for others to depend on makes sense and having it in a package manager that only handles standalone tools / phars makes no sense.

The dependency definition of this package are very broad by design: It allows for easier use in existing code bases.
